export type Word = {
  readonly display: string
  readonly kana: string
}

/**
 * お題60語。単価はゲーム側で `kana` の長さから動的に決める（本家準拠）。
 */
export const WORDS: readonly Word[] = [
  { display: '寿司', kana: 'すし' },
  { display: '醤油', kana: 'しょうゆ' },
  { display: '玉子', kana: 'たまご' },
  { display: '鮪', kana: 'まぐろ' },
  { display: '鰤', kana: 'ぶり' },
  { display: '鯛', kana: 'たい' },
  { display: '鰈', kana: 'かれい' },
  { display: '穴子', kana: 'あなご' },
  { display: '鰆', kana: 'さわら' },
  { display: '鰺', kana: 'あじ' },
  { display: '鯖', kana: 'さば' },
  { display: '鰹', kana: 'かつお' },
  { display: '海老', kana: 'えび' },
  { display: '蟹', kana: 'かに' },
  { display: '烏賊', kana: 'いか' },
  { display: '蛸', kana: 'たこ' },
  { display: '貝', kana: 'かい' },
  { display: '帆立', kana: 'ほたて' },
  { display: '牡蠣', kana: 'かき' },
  { display: '鰊', kana: 'にしん' },
  { display: '雲丹', kana: 'うに' },
  { display: '数の子', kana: 'かずのこ' },
  { display: '筋子', kana: 'すじこ' },
  { display: '軍艦', kana: 'ぐんかん' },
  { display: '巻物', kana: 'まきもの' },
  { display: '手巻き', kana: 'てまき' },
  { display: '軍艦巻き', kana: 'ぐんかんまき' },
  { display: '刺身', kana: 'さしみ' },
  { display: '握り', kana: 'にぎり' },
  { display: '押し寿司', kana: 'おしずし' },
  { display: '稲荷寿司', kana: 'いなりずし' },
  { display: '茶碗蒸し', kana: 'ちゃわんむし' },
  { display: '味噌汁', kana: 'みそしる' },
  { display: '茶', kana: 'おちゃ' },
  { display: 'がり', kana: 'がり' },
  { display: '山葵', kana: 'わさび' },
  { display: '大将', kana: 'たいしょう' },
  { display: '板前', kana: 'いたまえ' },
  { display: '出前', kana: 'でまえ' },
  { display: '回転寿司', kana: 'かいてんずし' },
  { display: '職人', kana: 'しょくにん' },
  { display: '仕入れ', kana: 'しいれ' },
  { display: '旬', kana: 'しゅん' },
  { display: '新鮮', kana: 'しんせん' },
  { display: '注文', kana: 'ちゅうもん' },
  { display: '会計', kana: 'かいけい' },
  { display: '常連', kana: 'じょうれん' },
  { display: '暖簾', kana: 'のれん' },
  { display: '湯呑み', kana: 'ゆのみ' },
  { display: '割り箸', kana: 'わりばし' },
  { display: '醤油差し', kana: 'しょうゆさし' },
  { display: 'お通し', kana: 'おとおし' },
  { display: '追加', kana: 'ついか' },
  { display: '満腹', kana: 'まんぷく' },
  { display: '食べ放題', kana: 'たべほうだい' },
  { display: '一人前', kana: 'いちにんまえ' },
  { display: '本日限定', kana: 'ほんじつげんてい' },
  { display: '大トロ', kana: 'おおとろ' },
  { display: '中トロ', kana: 'ちゅうとろ' },
  { display: '赤身', kana: 'あかみ' },
]
